# 测试环境
server:
  port: 80
  servlet:
    context-path: /

#配置日志 使用控制台输出
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #配置逻辑删除  已经删除了置为1  未删除置为0
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.141:3306/markquestion?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #解决出现Failed to start bean ‘documentationPluginsBootstrapper’错误
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  security:
    user:
      name: 123
      password: 123
  servlet:
    # 设置文件上传大小
    multipart:
      enabled: true
      max-file-size: 40GB #单个数据大小
      file-size-threshold: 0
      max-request-size: 40GB #总数据大小
  web:
    resources:
      static-locations: file:/markquestion,classpath:/static